export const TRACKING_COAST_MS = 320
export const TRACKING_EVIDENCE_MAX_AGE_MS = 700
export const TRACKING_ACTION_ANCHOR_MAX_AGE_MS = 900
export const TRACKING_BRIDGE_MAX_ANCHOR_AGE_MS = 1_600
export const TRACKING_MAX_FRAME_GAP_MS = 220

export const TRACKING_CAPTURE_BUDGET_MS = 10
export const TRACKING_CAPTURE_MAX_INTERVAL_MS = 120
